# Form implementation generated from reading ui file 'qt.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMessageBox
import re
import pandas as pd
import hashlib
import rsa
import rc4

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1242, 767)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 40, 1221, 621))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(46)
        self.tableWidget.setRowCount(0)
        for x in range(46):  
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget.setHorizontalHeaderItem(x, item)
            self.tableWidget.setItem(0, x, QtWidgets.QTableWidgetItem())
        
        self.tableWidget.setEditTriggers(QtWidgets.QTableWidget.EditTrigger.NoEditTriggers) 
        self.tableWidget.itemClicked.connect(self.on_item_clicked)  

        

        self.decrypted = False
        self.rsa_keys_added = False
        
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 1221, 20))
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(1100, 670, 131, 34))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.openAddStudentDialog)
        self.pushButton.setDisabled(True)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1242, 30))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuRSA = QtWidgets.QMenu(parent=self.menubar)
        self.menuRSA.setObjectName("menuRSA")
        self.menuAES = QtWidgets.QMenu(parent=self.menubar)
        self.menuAES.setObjectName("menuAES")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionTambah_Mata_Kuliah = QtGui.QAction(parent=MainWindow)
        self.actionTambah_Mata_Kuliah.setObjectName("actionTambah_Mata_Kuliah")
        self.actionTambah_Mata_Kuliah.triggered.connect(self.openAddMatkulDialog)
        self.actionEnkripsi_Basis_Data = QtGui.QAction(parent=MainWindow)
        self.actionEnkripsi_Basis_Data.setObjectName("actionEnkripsi_Basis_Data")
        self.actionEnkripsi_Basis_Data.setDisabled(True)
        self.actionDekripsi_Basis_Data = QtGui.QAction(parent=MainWindow)
        self.actionEnkripsi_Basis_Data.triggered.connect(self.encrypt)
        self.actionDekripsi_Basis_Data.setObjectName("actionDekripsi_Basis_Data")
        self.actionDekripsi_Basis_Data.triggered.connect(self.decrypt)
        self.actionBangkitkan_Kunci_RSA = QtGui.QAction(parent=MainWindow)
        self.actionBangkitkan_Kunci_RSA.setObjectName("actionBangkitkan_Kunci_RSA")
        self.actionBangkitkan_Kunci_RSA.triggered.connect(self.genKey)
        self.actionLoad_Kunci_RSA = QtGui.QAction(parent=MainWindow)
        self.actionLoad_Kunci_RSA.setObjectName("actionLoad_Kunci_RSA")
        self.actionLoad_Kunci_RSA.triggered.connect(self.loadKey)
        self.actionDekripsi_Laporan = QtGui.QAction(parent=MainWindow)
        self.actionDekripsi_Laporan.setObjectName("actionDekripsi_Laporan")
        self.menuFile.addAction(self.actionTambah_Mata_Kuliah)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionEnkripsi_Basis_Data)
        self.menuFile.addAction(self.actionDekripsi_Basis_Data)
        self.menuRSA.addAction(self.actionBangkitkan_Kunci_RSA)
        self.menuRSA.addAction(self.actionLoad_Kunci_RSA)
        self.menuAES.addAction(self.actionDekripsi_Laporan)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuRSA.menuAction())
        self.menubar.addAction(self.menuAES.menuAction())

        self.load_data("db/nilai_mahasiswa.csv")
        self.load_matkul("db/matkul.csv")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def loadKey(self):

        filename = QtWidgets.QFileDialog.getOpenFileName(self.mainwindow,"Pilih file",filter="pri(*.pri)")[0]

        try: 
            
            x = {}

            with open(filename,"r") as file:   

                params = file.readlines()

            if len(params) != 5:
                raise ValueError("file gk valid")
            else:
                for param in params:
                    if "=" in param:
                        key, value = param.split("=")
                        key = key.strip()
                        value = int(value.strip())
                        x[key] = value
                    else:
                        raise ValueError("file gk valid")
                valid = rsa.rsaValid(x["p"],x["q"],x["e"])
                if valid:
                    self.rsa_keys = {"public" : {"e" : x["e"],"n" : x["n"]}, "private" : {"d" : x["d"],"n": x["n"]}}
                    self.rsa_keys_added = True
                    if (self.rsa_keys_added and self.decrypted):
                        self.pushButton.setDisabled(False)
                    msg = QtWidgets.QMessageBox.information(None,f"Kunci RSA Berhasil Dibaca!",f"Kunci RSA berhasil dibaca dari file {filename}!")
                else:
                    msg = QtWidgets.QMessageBox.information(None,f"Kunci RSA Gagal Dibaca!",f"Kunci RSA tidak valid!")
                
        
        except:

            msg = QtWidgets.QMessageBox.information(None,f"Kunci RSA Gagal Dibaca!",f"Kunci RSA tidak valid!")

    def genKey(self):

        result = rsa.rsaGenerateKeyPair()

        self.rsa_keys = result["key"]
        self.rsa_keys_added = True

        if (self.rsa_keys_added and self.decrypted):
            self.pushButton.setDisabled(False)

        filename = rsa.rsaSaveKeyPair("kaprodi",result)

        msg = QtWidgets.QMessageBox.information(None,f"Kunci RSA Berhasil Dibangkitkan!",f"Kunci RSA baru telah dibangkitkan untuk kaprodi! Kunci telah disimpan sebagai {filename}.")
    
    def encrypt(self):
        dialog = QtWidgets.QDialog()
        dialog.ui = Ui_Dialog_3()
        dialog.ui.setupUi(dialog,self)
        dialog.exec()

    def decrypt(self):
        dialog = QtWidgets.QDialog()
        dialog.ui = Ui_Dialog_4()
        dialog.ui.setupUi(dialog,self)
        dialog.exec()

    def openAddStudentDialog(self):
        dialog = QtWidgets.QDialog()
        dialog.ui = Ui_Dialog()
        dialog.ui.setupUi(dialog,self)
        dialog.exec()
        

    def openAddMatkulDialog(self):
        dialog = QtWidgets.QDialog()
        dialog.ui = Ui_Dialog2()
        dialog.ui.setupUi(dialog,self)
        dialog.exec()

    def on_item_clicked(self, item):
        # Function to handle item click
        dialog = QMessageBox()
        dialog.setWindowTitle("Action")
        dialog.setText("Select Action")
        dialog.addButton("Verify Signature",QMessageBox.ButtonRole.ActionRole)
        dialog.addButton("Export as PDF",QMessageBox.ButtonRole.ActionRole)
        dialog.addButton("Cancel",QMessageBox.ButtonRole.ActionRole)

        self.currentrow = self.database_transkrip.iloc[item.row()]
        x = dialog.exec()

        if x == 0:
            if self.verifySign():
                msg = QtWidgets.QMessageBox.information(None,f"Signature sesuai!",f"Signature sesuai dengan isi baris.")
            else:
                msg = QtWidgets.QMessageBox.information(None,f"Signature tidak sesuai!",f"Signature tidak sesuai dengan isi baris.")

    def verifySign(self):

        row = self.currentrow

        row_excluded = row[:-2]

        s = hashlib.sha3_256()

        data = ''.join(row_excluded.astype(str))

        s.update(bytes(data,"utf-8"))

        public_key = row["Public_Key"].split(";")
        e = public_key[0].split("=")[1]
        n = public_key[1].split("=")[1]
        public_key = {"public" : {"e" : int(e),"n" : int(n)}}

        print(row["Sign"])

        decrypted = rsa.rsaDecryptText(str(row["Sign"]),public_key["public"])
        decrypted = decrypted[:len(str(s.hexdigest()))]

        if decrypted != str(s.hexdigest()):
            return False
        else:
            return True

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "NIM"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nama Mahasiswa"))

        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Kode MK1"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Nama MK1"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Nilai MK1"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "SKS MK1"))

        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Kode MK1"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Nama MK1"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Nilai MK1"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "SKS MK2"))

        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "Kode MK3"))
        item = self.tableWidget.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "Nama MK3"))
        item = self.tableWidget.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "Nilai MK3"))
        item = self.tableWidget.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "SKS MK3"))

        item = self.tableWidget.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow", "Kode MK4"))
        item = self.tableWidget.horizontalHeaderItem(15)
        item.setText(_translate("MainWindow", "Nama MK4"))
        item = self.tableWidget.horizontalHeaderItem(16)
        item.setText(_translate("MainWindow", "Nilai MK4"))
        item = self.tableWidget.horizontalHeaderItem(17)
        item.setText(_translate("MainWindow", "SKS MK4"))

        item = self.tableWidget.horizontalHeaderItem(18)
        item.setText(_translate("MainWindow", "Kode MK5"))
        item = self.tableWidget.horizontalHeaderItem(19)
        item.setText(_translate("MainWindow", "Nama MK5"))
        item = self.tableWidget.horizontalHeaderItem(20)
        item.setText(_translate("MainWindow", "Nilai MK5"))
        item = self.tableWidget.horizontalHeaderItem(21)
        item.setText(_translate("MainWindow", "SKS MK5"))

        item = self.tableWidget.horizontalHeaderItem(22)
        item.setText(_translate("MainWindow", "Kode MK6"))
        item = self.tableWidget.horizontalHeaderItem(23)
        item.setText(_translate("MainWindow", "Nama MK6"))
        item = self.tableWidget.horizontalHeaderItem(24)
        item.setText(_translate("MainWindow", "Nilai MK6"))
        item = self.tableWidget.horizontalHeaderItem(25)
        item.setText(_translate("MainWindow", "SKS MK6"))

        item = self.tableWidget.horizontalHeaderItem(26)
        item.setText(_translate("MainWindow", "Kode MK7"))
        item = self.tableWidget.horizontalHeaderItem(27)
        item.setText(_translate("MainWindow", "Nama MK7"))
        item = self.tableWidget.horizontalHeaderItem(28)
        item.setText(_translate("MainWindow", "Nilai MK7"))
        item = self.tableWidget.horizontalHeaderItem(29)
        item.setText(_translate("MainWindow", "SKS MK7"))

        item = self.tableWidget.horizontalHeaderItem(30)
        item.setText(_translate("MainWindow", "Kode MK8"))
        item = self.tableWidget.horizontalHeaderItem(31)
        item.setText(_translate("MainWindow", "Nama MK8"))
        item = self.tableWidget.horizontalHeaderItem(32)
        item.setText(_translate("MainWindow", "Nilai MK8"))
        item = self.tableWidget.horizontalHeaderItem(33)
        item.setText(_translate("MainWindow", "SKS MK8"))

        item = self.tableWidget.horizontalHeaderItem(34)
        item.setText(_translate("MainWindow", "Kode MK9"))
        item = self.tableWidget.horizontalHeaderItem(35)
        item.setText(_translate("MainWindow", "Nama MK9"))
        item = self.tableWidget.horizontalHeaderItem(36)
        item.setText(_translate("MainWindow", "Nilai MK9"))
        item = self.tableWidget.horizontalHeaderItem(37)
        item.setText(_translate("MainWindow", "SKS MK9"))

        item = self.tableWidget.horizontalHeaderItem(38)
        item.setText(_translate("MainWindow", "Kode MK10"))
        item = self.tableWidget.horizontalHeaderItem(39)
        item.setText(_translate("MainWindow", "Nama MK10"))
        item = self.tableWidget.horizontalHeaderItem(40)
        item.setText(_translate("MainWindow", "Nilai MK10"))
        item = self.tableWidget.horizontalHeaderItem(41)
        item.setText(_translate("MainWindow", "SKS MK10"))

        item = self.tableWidget.horizontalHeaderItem(42)
        item.setText(_translate("MainWindow", "Total SKS"))
        item = self.tableWidget.horizontalHeaderItem(43)
        item.setText(_translate("MainWindow", "IPK"))
        item = self.tableWidget.horizontalHeaderItem(44)
        item.setText(_translate("MainWindow", "Tanda Tangan Digital"))
        item = self.tableWidget.horizontalHeaderItem(45)
        item.setText(_translate("MainWindow", "Kunci Publik Kaprodi"))

        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("MainWindow", "Basis Data Transkrip Nilai"))
        self.pushButton.setText(_translate("MainWindow", "Tambah Mahasiswa"))
        self.menuFile.setTitle(_translate("MainWindow", "&Data"))
        self.menuRSA.setTitle(_translate("MainWindow", "RSA"))
        self.menuAES.setTitle(_translate("MainWindow", "AES"))
        self.actionTambah_Mata_Kuliah.setText(_translate("MainWindow", "Tambah Mata Kuliah"))
        self.actionDekripsi_Basis_Data.setText(_translate("MainWindow", "Dekripsi Basis Data"))
        self.actionEnkripsi_Basis_Data.setText(_translate("MainWindow", "Enkripsi dan Simpan Basis Data"))
        self.actionBangkitkan_Kunci_RSA.setText(_translate("MainWindow", "Bangkitkan Kunci RSA"))
        self.actionLoad_Kunci_RSA.setText(_translate("MainWindow", "Load Kunci RSA"))
        self.actionDekripsi_Laporan.setText(_translate("MainWindow", "Dekripsi Laporan"))

    def load_data(self, filePath):
        df = pd.read_csv(filePath)
        self.database_transkrip = df
        self.tableWidget.setRowCount(len(df.index))
        if not df.empty:
            for row in df.iterrows():
                values = row[1]
                for col_index, value in enumerate(values):
                    self.tableWidget.setItem(row[0], col_index, QtWidgets.QTableWidgetItem(str(value)))
        else:
            self.decrypted = True
            self.actionDekripsi_Basis_Data.setDisabled(True)

    def update_data(self):
        if not self.database_transkrip.empty:
            self.actionEnkripsi_Basis_Data.setDisabled(False)
            self.tableWidget.setRowCount(len(self.database_transkrip.index))
            for row in self.database_transkrip.iterrows():
                values = row[1]
                for col_index, value in enumerate(values):
                    self.tableWidget.setItem(row[0], col_index, QtWidgets.QTableWidgetItem(str(value)))
    
    def load_matkul(self, filePath):
        df = pd.read_csv(filePath)
        self.database_matakuliah = df

class Ui_Dialog(QtWidgets.QDialog):
    def setupUi(self, Dialog, parent):
        Dialog.setObjectName("Dialog")
        Dialog.resize(862, 324)
        self.parent = parent
        self.database_matakuliah = parent.database_matakuliah
        self.database_transkrip = parent.database_transkrip
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(10, 290, 841, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.buttonBox.button(QtWidgets.QDialogButtonBox.StandardButton.Ok).setEnabled(False)
        self.buttonBox.button(QtWidgets.QDialogButtonBox.StandardButton.Ok).clicked.connect(self.add)

        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(10, 50, 61, 31))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(80, 10, 771, 32))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 61, 31))
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(80, 50, 771, 32))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 90, 61, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=Dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 130, 61, 31))
        self.label_4.setObjectName("label_4")
        self.comboBox = QtWidgets.QComboBox(parent=Dialog)
        self.comboBox.setGeometry(QtCore.QRect(80, 90, 281, 32))
        self.comboBox.setObjectName("comboBox")
        self.label_5 = QtWidgets.QLabel(parent=Dialog)
        self.label_5.setGeometry(QtCore.QRect(440, 90, 61, 31))
        self.label_5.setObjectName("label_5")
        self.comboBox_2 = QtWidgets.QComboBox(parent=Dialog)
        self.comboBox_2.setGeometry(QtCore.QRect(370, 90, 51, 32))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.label_6 = QtWidgets.QLabel(parent=Dialog)
        self.label_6.setGeometry(QtCore.QRect(10, 170, 61, 31))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=Dialog)
        self.label_7.setGeometry(QtCore.QRect(10, 210, 61, 31))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(parent=Dialog)
        self.label_8.setGeometry(QtCore.QRect(10, 250, 61, 31))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(parent=Dialog)
        self.label_9.setGeometry(QtCore.QRect(440, 130, 61, 31))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(parent=Dialog)
        self.label_10.setGeometry(QtCore.QRect(440, 170, 61, 31))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(parent=Dialog)
        self.label_11.setGeometry(QtCore.QRect(440, 210, 61, 31))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(parent=Dialog)
        self.label_12.setGeometry(QtCore.QRect(440, 250, 61, 31))
        self.label_12.setObjectName("label_12")
        self.comboBox_3 = QtWidgets.QComboBox(parent=Dialog)
        self.comboBox_3.setGeometry(QtCore.QRect(80, 130, 281, 32))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_4 = QtWidgets.QComboBox(parent=Dialog)
        self.comboBox_4.setGeometry(QtCore.QRect(370, 130, 51, 32))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_5 = QtWidgets.QComboBox(parent=Dialog)
        self.comboBox_5.setGeometry(QtCore.QRect(80, 170, 281, 32))
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_6 = QtWidgets.QComboBox(parent=Dialog)
        self.comboBox_6.setGeometry(QtCore.QRect(370, 170, 51, 32))
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_7 = QtWidgets.QComboBox(parent=Dialog)
        self.comboBox_7.setGeometry(QtCore.QRect(80, 210, 281, 32))
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_8 = QtWidgets.QComboBox(parent=Dialog)
        self.comboBox_8.setGeometry(QtCore.QRect(370, 210, 51, 32))
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.comboBox_9 = QtWidgets.QComboBox(parent=Dialog)
        self.comboBox_9.setGeometry(QtCore.QRect(80, 250, 281, 32))
        self.comboBox_9.setObjectName("comboBox_9")
        self.comboBox_10 = QtWidgets.QComboBox(parent=Dialog)
        self.comboBox_10.setGeometry(QtCore.QRect(370, 250, 51, 32))
        self.comboBox_10.setObjectName("comboBox_10")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_11 = QtWidgets.QComboBox(parent=Dialog)
        self.comboBox_11.setGeometry(QtCore.QRect(510, 90, 281, 32))
        self.comboBox_11.setObjectName("comboBox_11")
        self.comboBox_12 = QtWidgets.QComboBox(parent=Dialog)
        self.comboBox_12.setGeometry(QtCore.QRect(800, 90, 51, 32))
        self.comboBox_12.setObjectName("comboBox_12")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_13 = QtWidgets.QComboBox(parent=Dialog)
        self.comboBox_13.setGeometry(QtCore.QRect(510, 130, 281, 32))
        self.comboBox_13.setObjectName("comboBox_13")
        self.comboBox_14 = QtWidgets.QComboBox(parent=Dialog)
        self.comboBox_14.setGeometry(QtCore.QRect(800, 130, 51, 32))
        self.comboBox_14.setObjectName("comboBox_14")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_15 = QtWidgets.QComboBox(parent=Dialog)
        self.comboBox_15.setGeometry(QtCore.QRect(510, 170, 281, 32))
        self.comboBox_15.setObjectName("comboBox_15")
        self.comboBox_16 = QtWidgets.QComboBox(parent=Dialog)
        self.comboBox_16.setGeometry(QtCore.QRect(800, 170, 51, 32))
        self.comboBox_16.setObjectName("comboBox_16")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_17 = QtWidgets.QComboBox(parent=Dialog)
        self.comboBox_17.setGeometry(QtCore.QRect(510, 210, 281, 32))
        self.comboBox_17.setObjectName("comboBox_17")
        self.comboBox_18 = QtWidgets.QComboBox(parent=Dialog)
        self.comboBox_18.setGeometry(QtCore.QRect(800, 210, 51, 32))
        self.comboBox_18.setObjectName("comboBox_18")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_19 = QtWidgets.QComboBox(parent=Dialog)
        self.comboBox_19.setGeometry(QtCore.QRect(510, 250, 281, 32))
        self.comboBox_19.setObjectName("comboBox_19")
        self.comboBox_20 = QtWidgets.QComboBox(parent=Dialog)
        self.comboBox_20.setGeometry(QtCore.QRect(800, 250, 51, 32))
        self.comboBox_20.setObjectName("comboBox_20")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")

        result = []
        for index, row in self.database_matakuliah.iterrows():
            concatenated_string = " ".join([f'{row["Kode"]} -  {row["Nama"]} - {row["SKS"]} SKS'])
            result.append(concatenated_string)


        self.odd_comboboxes = [self.comboBox, self.comboBox_3, self.comboBox_5, self.comboBox_7, self.comboBox_9, self.comboBox_11, self.comboBox_13, self.comboBox_15, self.comboBox_17, self.comboBox_19]
        self.even_comboboxes = [self.comboBox_2, self.comboBox_4, self.comboBox_6, self.comboBox_8, self.comboBox_10, self.comboBox_12, self.comboBox_14, self.comboBox_16, self.comboBox_18, self.comboBox_20]
        for combobox in self.odd_comboboxes:
            combobox.addItems(result)

        self.lineEdit.textChanged.connect(self.validate_inputs)
        self.lineEdit_2.textChanged.connect(self.validate_inputs)

        for combobox in self.odd_comboboxes:
            combobox.currentIndexChanged.connect(self.validate_inputs)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) 
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def validate_inputs(self):
        nama_valid =  re.fullmatch(r'^[A-Za-z ]+$', self.lineEdit_2.text()) is not None
        nim_valid = re.fullmatch(r'\d{8}', self.lineEdit.text()) is not None
        if nama_valid and nim_valid and self.unique_combobox_selections():
            self.buttonBox.button(QtWidgets.QDialogButtonBox.StandardButton.Ok).setEnabled(True)
        else:
            self.buttonBox.button(QtWidgets.QDialogButtonBox.StandardButton.Ok).setEnabled(False)

    def unique_combobox_selections(self):
        seen = set()
        for combobox in self.odd_comboboxes:
            selection = combobox.currentText()
            if selection in seen:
                return False
            seen.add(selection)
        return True
    
    def add(self):
        nama = self.lineEdit_2.text()
        nim = self.lineEdit.text()
        matkul = []
        total = 0
        sks = 0

        nilai_index = {
            "A" : 4.0,
            "AB" : 3.5,
            "B" : 3.0,
            "BC" : 2.5,
            "C" : 2.0,
            "D" : 1.0,
            "E" : 0.0
        }

        for i in range(len(self.even_comboboxes)):
            mk = [x.strip() for x in self.odd_comboboxes[i].currentText().split(" - ")]
            total += int(mk[2].split(" ")[0]) * nilai_index[self.even_comboboxes[i].currentText()]
            matkul.append(mk[0])
            matkul.append(mk[1])
            matkul.append(self.even_comboboxes[i].currentText())
            matkul.append(mk[2].split(" ")[0])
            sks += int(mk[2].split(" ")[0])

        final = [nim, nama] + matkul + [str(total), str(round(total/sks,2))]

        s = hashlib.sha3_256()
        s.update(bytes("".join(final),"utf-8"))

        sign = rsa.rsaEncryptText(str(s.hexdigest()) + "   ",self.parent.rsa_keys["private"])

        public_key = f"e={self.parent.rsa_keys["public"]["e"]};n={self.parent.rsa_keys["public"]["n"]}"

        final = final + [sign, public_key]
        
        row = pd.DataFrame([final], columns=self.database_transkrip.columns)

        self.parent.database_transkrip = pd.concat([self.database_transkrip, row], ignore_index=True)
        self.parent.update_data()

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Nama"))
        self.label_2.setText(_translate("Dialog", "NIM"))
        self.label_3.setText(_translate("Dialog", "MK1"))
        self.label_4.setText(_translate("Dialog", "MK2"))
        self.label_5.setText(_translate("Dialog", "MK6"))
        self.comboBox_2.setItemText(0, _translate("Dialog", "A"))
        self.comboBox_2.setItemText(1, _translate("Dialog", "AB"))
        self.comboBox_2.setItemText(2, _translate("Dialog", "B"))
        self.comboBox_2.setItemText(3, _translate("Dialog", "BC"))
        self.comboBox_2.setItemText(4, _translate("Dialog", "C"))
        self.comboBox_2.setItemText(5, _translate("Dialog", "D"))
        self.comboBox_2.setItemText(6, _translate("Dialog", "E"))
        self.label_6.setText(_translate("Dialog", "MK3"))
        self.label_7.setText(_translate("Dialog", "MK4"))
        self.label_8.setText(_translate("Dialog", "MK5"))
        self.label_9.setText(_translate("Dialog", "MK7"))
        self.label_10.setText(_translate("Dialog", "MK8"))
        self.label_11.setText(_translate("Dialog", "MK9"))
        self.label_12.setText(_translate("Dialog", "MK10"))
        self.comboBox_4.setItemText(0, _translate("Dialog", "A"))
        self.comboBox_4.setItemText(1, _translate("Dialog", "AB"))
        self.comboBox_4.setItemText(2, _translate("Dialog", "B"))
        self.comboBox_4.setItemText(3, _translate("Dialog", "BC"))
        self.comboBox_4.setItemText(4, _translate("Dialog", "C"))
        self.comboBox_4.setItemText(5, _translate("Dialog", "D"))
        self.comboBox_4.setItemText(6, _translate("Dialog", "E"))
        self.comboBox_6.setItemText(0, _translate("Dialog", "A"))
        self.comboBox_6.setItemText(1, _translate("Dialog", "AB"))
        self.comboBox_6.setItemText(2, _translate("Dialog", "B"))
        self.comboBox_6.setItemText(3, _translate("Dialog", "BC"))
        self.comboBox_6.setItemText(4, _translate("Dialog", "C"))
        self.comboBox_6.setItemText(5, _translate("Dialog", "D"))
        self.comboBox_6.setItemText(6, _translate("Dialog", "E"))
        self.comboBox_8.setItemText(0, _translate("Dialog", "A"))
        self.comboBox_8.setItemText(1, _translate("Dialog", "AB"))
        self.comboBox_8.setItemText(2, _translate("Dialog", "B"))
        self.comboBox_8.setItemText(3, _translate("Dialog", "BC"))
        self.comboBox_8.setItemText(4, _translate("Dialog", "C"))
        self.comboBox_8.setItemText(5, _translate("Dialog", "D"))
        self.comboBox_8.setItemText(6, _translate("Dialog", "E"))
        self.comboBox_10.setItemText(0, _translate("Dialog", "A"))
        self.comboBox_10.setItemText(1, _translate("Dialog", "AB"))
        self.comboBox_10.setItemText(2, _translate("Dialog", "B"))
        self.comboBox_10.setItemText(3, _translate("Dialog", "BC"))
        self.comboBox_10.setItemText(4, _translate("Dialog", "C"))
        self.comboBox_10.setItemText(5, _translate("Dialog", "D"))
        self.comboBox_10.setItemText(6, _translate("Dialog", "E"))
        self.comboBox_12.setItemText(0, _translate("Dialog", "A"))
        self.comboBox_12.setItemText(1, _translate("Dialog", "AB"))
        self.comboBox_12.setItemText(2, _translate("Dialog", "B"))
        self.comboBox_12.setItemText(3, _translate("Dialog", "BC"))
        self.comboBox_12.setItemText(4, _translate("Dialog", "C"))
        self.comboBox_12.setItemText(5, _translate("Dialog", "D"))
        self.comboBox_12.setItemText(6, _translate("Dialog", "E"))
        self.comboBox_14.setItemText(0, _translate("Dialog", "A"))
        self.comboBox_14.setItemText(1, _translate("Dialog", "AB"))
        self.comboBox_14.setItemText(2, _translate("Dialog", "B"))
        self.comboBox_14.setItemText(3, _translate("Dialog", "BC"))
        self.comboBox_14.setItemText(4, _translate("Dialog", "C"))
        self.comboBox_14.setItemText(5, _translate("Dialog", "D"))
        self.comboBox_14.setItemText(6, _translate("Dialog", "E"))
        self.comboBox_16.setItemText(0, _translate("Dialog", "A"))
        self.comboBox_16.setItemText(1, _translate("Dialog", "AB"))
        self.comboBox_16.setItemText(2, _translate("Dialog", "B"))
        self.comboBox_16.setItemText(3, _translate("Dialog", "BC"))
        self.comboBox_16.setItemText(4, _translate("Dialog", "C"))
        self.comboBox_16.setItemText(5, _translate("Dialog", "D"))
        self.comboBox_16.setItemText(6, _translate("Dialog", "E"))
        self.comboBox_18.setItemText(0, _translate("Dialog", "A"))
        self.comboBox_18.setItemText(1, _translate("Dialog", "AB"))
        self.comboBox_18.setItemText(2, _translate("Dialog", "B"))
        self.comboBox_18.setItemText(3, _translate("Dialog", "BC"))
        self.comboBox_18.setItemText(4, _translate("Dialog", "C"))
        self.comboBox_18.setItemText(5, _translate("Dialog", "D"))
        self.comboBox_18.setItemText(6, _translate("Dialog", "E"))
        self.comboBox_20.setItemText(0, _translate("Dialog", "A"))
        self.comboBox_20.setItemText(1, _translate("Dialog", "AB"))
        self.comboBox_20.setItemText(2, _translate("Dialog", "B"))
        self.comboBox_20.setItemText(3, _translate("Dialog", "BC"))
        self.comboBox_20.setItemText(4, _translate("Dialog", "C"))
        self.comboBox_20.setItemText(5, _translate("Dialog", "D"))
        self.comboBox_20.setItemText(6, _translate("Dialog", "E"))

class Ui_Dialog2(QtWidgets.QDialog):
    def setupUi(self, Dialog, parent):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 182)
        self.parent = parent
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(10, 130, 381, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.buttonBox.button(QtWidgets.QDialogButtonBox.StandardButton.Ok).setEnabled(False)
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 61, 31))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(80, 10, 311, 32))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 61, 31))
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(80, 50, 311, 32))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.spinBox = QtWidgets.QSpinBox(parent=Dialog)
        self.spinBox.setGeometry(QtCore.QRect(80, 90, 52, 32))
        self.spinBox.setObjectName("spinBox")
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 90, 61, 31))
        self.label_3.setObjectName("label_3")

        self.buttonBox.accepted.connect(Dialog.accept) 
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.lineEdit.textChanged.connect(self.validate_inputs)
        self.lineEdit_2.textChanged.connect(self.validate_inputs)
        self.spinBox.valueChanged.connect(self.validate_inputs)

        self.retranslateUi(Dialog)

        self.buttonBox.accepted.connect(Dialog.accept) 
        self.buttonBox.accepted.connect(self.add) 
        self.buttonBox.rejected.connect(Dialog.reject)
        
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def validate_inputs(self):
        nama_valid = re.fullmatch(r'^[A-Za-z ]+$', self.lineEdit_2.text()) is not None
        nim_valid = re.fullmatch(r'^[A-Z]{2}\d{4}$', self.lineEdit.text()) is not None
        if nama_valid and nim_valid and self.spinBox.value() > 0 and (self.parent.database_matakuliah[self.parent.database_matakuliah['Kode'] == self.lineEdit_2.text()].empty):
            self.buttonBox.button(QtWidgets.QDialogButtonBox.StandardButton.Ok).setEnabled(True)
        else:
            self.buttonBox.button(QtWidgets.QDialogButtonBox.StandardButton.Ok).setEnabled(False)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Kode"))
        self.label_2.setText(_translate("Dialog", "Nama"))
        self.label_3.setText(_translate("Dialog", "SKS"))

    def add(self):
        nama = self.lineEdit.text()
        kode = self.lineEdit_2.text()
        sks = self.spinBox.value()

        final = [nama, kode, sks]
        
        row = pd.DataFrame([final], columns=self.parent.database_matakuliah.columns)

        self.parent.database_matakuliah = pd.concat([self.parent.database_matakuliah, row], ignore_index=True)
    
class Ui_Dialog_3(object):
    def setupUi(self, Dialog,parent):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 129)
        self.parent = parent
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(10, 90, 381, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.buttonBox.button(QtWidgets.QDialogButtonBox.StandardButton.Ok).setEnabled(False)
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 61, 31))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(80, 10, 311, 32))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 61, 31))
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(80, 50, 311, 32))
        self.lineEdit_2.setObjectName("lineEdit_2")

        self.buttonBox.accepted.connect(Dialog.accept) 
        self.buttonBox.accepted.connect(self.encrypt) 
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.lineEdit.textChanged.connect(self.validate_inputs)
        self.lineEdit_2.textChanged.connect(self.validate_inputs)        

        self.retranslateUi(Dialog)

        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Key"))
        self.label_2.setText(_translate("Dialog", "Vigenere"))

    def validate_inputs(self):
        nama_valid = re.fullmatch(r'^[A-Za-z]+$', self.lineEdit_2.text()) is not None
        nim_valid = re.fullmatch(r'^[A-Za-z]+$', self.lineEdit.text()) is not None
        if nama_valid and nim_valid:
            self.buttonBox.button(QtWidgets.QDialogButtonBox.StandardButton.Ok).setEnabled(True)
        else:
            self.buttonBox.button(QtWidgets.QDialogButtonBox.StandardButton.Ok).setEnabled(False)

    def encrypt(self):

        for i in range(self.parent.database_transkrip.shape[0]):
            for j in range(self.parent.database_transkrip.shape[1]):
                self.parent.database_transkrip.iat[i, j] = rc4.base64Encrypt(rc4.rc4(self.parent.database_transkrip.iat[i, j],self.lineEdit_2.text(),self.lineEdit.text()))
                
        self.parent.update_data()
        self.parent.pushButton.setDisabled(True)
        self.parent.actionEnkripsi_Basis_Data.setDisabled(True)
        self.parent.actionDekripsi_Basis_Data.setDisabled(False)
        self.parent.database_transkrip.to_csv("db/nilai_mahasiswa.csv",index=False)

class Ui_Dialog_4(object):
    def setupUi(self, Dialog,parent):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 129)
        self.parent = parent
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(10, 90, 381, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.buttonBox.button(QtWidgets.QDialogButtonBox.StandardButton.Ok).setEnabled(False)
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 61, 31))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(80, 10, 311, 32))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 61, 31))
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(80, 50, 311, 32))
        self.lineEdit_2.setObjectName("lineEdit_2")

        self.buttonBox.accepted.connect(Dialog.accept) 
        self.buttonBox.accepted.connect(self.decrypt) 
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.lineEdit.textChanged.connect(self.validate_inputs)
        self.lineEdit_2.textChanged.connect(self.validate_inputs)        

        self.retranslateUi(Dialog)

        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Key"))
        self.label_2.setText(_translate("Dialog", "Vigenere"))

    def validate_inputs(self):
        nama_valid = re.fullmatch(r'^[A-Za-z]+$', self.lineEdit_2.text()) is not None
        nim_valid = re.fullmatch(r'^[A-Za-z]+$', self.lineEdit.text()) is not None
        if nama_valid and nim_valid:
            self.buttonBox.button(QtWidgets.QDialogButtonBox.StandardButton.Ok).setEnabled(True)
        else:
            self.buttonBox.button(QtWidgets.QDialogButtonBox.StandardButton.Ok).setEnabled(False)

    def decrypt(self):

        for i in range(self.parent.database_transkrip.shape[0]):
            for j in range(self.parent.database_transkrip.shape[1]):
                self.parent.database_transkrip.iat[i, j] = rc4.rc4(rc4.base64Decrypt(self.parent.database_transkrip.iat[i, j]),self.lineEdit_2.text(),self.lineEdit.text())
                
        self.parent.update_data()
        self.parent.pushButton.setDisabled(False)
        self.parent.actionEnkripsi_Basis_Data.setDisabled(False)
        self.parent.actionDekripsi_Basis_Data.setDisabled(True)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
